emart/emart_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('buyers.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
    path('payments/', include('payments.urls')),
    path('sellers/', include('sellers.urls')),
    path('users/', include('users.urls')),
    path('reviews/', include('reviews.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

emart/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('', views.order_list, name='order_list'),
    path('<int:pk>/', views.order_detail, name='order_detail'),
]

emart/products/urls.py
from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [
    path('', views.product_list, name='list'),
    path('<slug:slug>/', views.product_detail, name='detail'),
]

emart/users/urls.py
from django.urls import path
from . import views

app_name = "users"   # <-- VERY IMPORTANT

urlpatterns = [
    path('login/', views.login_view, name="login"),
    path('register/', views.register_view, name="register"),
    path('logout/', views.logout_view, name="logout"),
]

emart/templates/base.html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>EMART</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
   <div class="container">
     <a class="navbar-brand" href="{% url 'home' %}">EMART</a>
     <div class="collapse navbar-collapse">
       <ul class="navbar-nav ms-auto">
         <li class="nav-item"><a class="nav-link" href="{% url 'products:list' %}">Products</a></li>
         <li class="nav-item"><a class="nav-link" href="{% url 'cart_detail' %}">Cart</a></li>
         {% if user.is_authenticated %}
           <li class="nav-item"><a class="nav-link" href="{% url 'orders:order_list' %}">Orders</a></li>
           <li class="nav-item"><a class="nav-link" href="{% url 'admin:logout' %}">Logout</a></li>
         {% else %}
           <li class="nav-item"><a class="nav-link" href="{% url 'users:register' %}">Register</a></li>
           <li class="nav-item"><a class="nav-link" href="{% url 'admin:login' %}">Login</a></li>
         {% endif %}
       </ul>
     </div>
   </div>
  </nav>
  <div class="container mt-4">
    {% block content %}{% endblock %}
  </div>
</body>
</html>